version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongo-prodis
    environment:
      - MONGO_INITDB_ROOT_USERNAME=crystelcare
      - MONGO_INITDB_ROOT_PASSWORD=zcd9YKC0fty_nmb6zun
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./data/mongodb/crystelcare.mongodb:/data/dump
      - ./backups/mongodb:/backup
      - ./backup-scripts/mongodb/mongodb-backup.sh:/backup.sh
      - ./backup-scripts/mongodb/cron/mongodb-backup:/etc/cron.d/mongodb-backup
    networks:
      - my_network
    entrypoint: |
      /bin/bash -c "
        apt-get update && 
        apt-get install -y cron awscli && 
        chmod +x /backup.sh && 
        crontab /etc/cron.d/mongodb-backup && 
        cron && 
        docker-entrypoint.sh mongod
      "

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-prodis
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=phippsy
      - RABBITMQ_DEFAULT_PASS=213cn5us
    restart: unless-stopped
    networks:
      - my_network

  redis:
    image: redis:latest
    container_name: redis-prodis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - my_network

networks:
  my_network:
    external: true

volumes:
  redis_data:
  mongo-data:
