version: '3.8'

secrets:
  api_env_file:
    file: ./env.php
  app_env_file:
    file: ./app.conf

services:
  app:
    # ports:
    #   - "5173:5173"
    secrets:
      - source: app_env_file
        target: /app/app.conf
    volumes:
      - ./app:/app
      - ./shared:/app/shared
      - /app/node_modules
    restart: unless-stopped
    networks:
      - my_network

  api:
    secrets:
      - source: api_env_file
        target: /var/www/prodis/env.php
    # ports:
    #   - "8090:8080"
    volumes:
      - ./api:/var/www/prodis/api
      - ./src:/var/www/prodis/src
      - ./servers:/var/www/prodis/servers
      - composer_cache:/tmp/cache
    restart: unless-stopped
    depends_on:
      - rabbitmq
      - redis
      - mongodb
    networks:
      - my_network

  mongodb:
    image: mongo
    container_name: mongo-prodis
    environment:
      - MONGO_INITDB_ROOT_USERNAME=crystelcare
      - MONGO_INITDB_ROOT_PASSWORD=zcd9YKC0fty_nmb6zun
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./data/mongodb/crystelcare.mongodb:/data/dump
    networks:
      - my_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-prodis
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=phippsy
      - RABBITMQ_DEFAULT_PASS=213cn5us
    restart: unless-stopped
    networks:
      - my_network

  redis:
    image: redis:latest
    container_name: redis-prodis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - my_network

networks:
  my_network:
    external: true

volumes:
  redis_data:
  mongo-data:
  composer_cache:
