version: '3.8'

secrets:
  api_env_file:
    file: ./env.php
  app_env_file:
    file: ./app.conf

services:
  app:
    # ports:
    #   - "5173:5173"
    secrets:
      - source: app_env_file
        target: /app/app.conf
    volumes:
      - ./app:/app
      - ./shared:/app/shared
      - /app/node_modules
    restart: unless-stopped
    networks:
      - my_network

  api:
    secrets:
      - source: api_env_file
        target: /var/www/prodis/env.php
    # ports:
    #   - "8090:8080"
    volumes:
      - ./api:/var/www/prodis/api
      - ./src:/var/www/prodis/src
      - ./servers:/var/www/prodis/servers
      - ./oauth-credentials.json:/var/www/prodis/oauth-credentials.json
      - composer_cache:/tmp/cache
    restart: unless-stopped
    networks:
      - my_network

networks:
  my_network:
    external: true

volumes:
  composer_cache:
