version: '3.8'

services:
  app:
    container_name: prodis-${DEVELOPER_NAME}-app
    build:
      context: .
      dockerfile: Dockerfile.app
      labels:
        - "maintainer=${DEVELOPER_NAME}"
    image: prodis-${DEVELOPER_NAME}-app:latest
    environment:
      - NODE_ENV=development
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prodis-${DEVELOPER_NAME}-app.service=prodis-${DEVELOPER_NAME}-app"
      - "traefik.http.routers.prodis-${DEVELOPER_NAME}-app.rule=Host(`app.prodis.${DEVELOPER_NAME}.phippsy.tech`)"
      - "traefik.http.routers.prodis-${DEVELOPER_NAME}-app.entrypoints=websecure"
      - "traefik.http.routers.prodis-${DEVELOPER_NAME}-app.tls.certresolver=myresolver"
      - "traefik.http.services.prodis-${DEVELOPER_NAME}-app.loadbalancer.server.port=5173"
      # - "traefik.http.routers.prodis-${DEVELOPER_NAME}-app.middlewares=error-pages@docker"

  api:
    container_name: prodis-${DEVELOPER_NAME}-api
    build:
      context: .
      dockerfile: Dockerfile.api
      labels:
        - "maintainer=${DEVELOPER_NAME}"
    image: prodis-${DEVELOPER_NAME}-api:latest
    labels:
      - "traefik.enable=true"
      # API
      - "traefik.http.routers.prodis-${DEVELOPER_NAME}-api.service=prodis-${DEVELOPER_NAME}-api"
      - "traefik.http.routers.prodis-${DEVELOPER_NAME}-api.rule=Host(`api.prodis.${DEVELOPER_NAME}.phippsy.tech`)"
      - "traefik.http.services.prodis-${DEVELOPER_NAME}-api.loadbalancer.server.port=8080"
      - "traefik.http.routers.prodis-${DEVELOPER_NAME}-api.entrypoints=websecure"
      - "traefik.http.routers.prodis-${DEVELOPER_NAME}-api.tls.certresolver=myresolver"

      # Webhooks
      - "traefik.http.routers.prodis-${DEVELOPER_NAME}-webhooks.service=prodis-${DEVELOPER_NAME}-webhooks"
      - "traefik.http.routers.prodis-${DEVELOPER_NAME}-webhooks.rule=Host(`webhooks.prodis.${DEVELOPER_NAME}.phippsy.tech`)"
      - "traefik.http.services.prodis-${DEVELOPER_NAME}-webhooks.loadbalancer.server.port=80"
      - "traefik.http.routers.prodis-${DEVELOPER_NAME}-webhooks.entrypoints=websecure"
      - "traefik.http.routers.prodis-${DEVELOPER_NAME}-webhooks.tls.certresolver=myresolver"

      # Websocket
      - "traefik.http.routers.prodis-${DEVELOPER_NAME}-wss.service=prodis-${DEVELOPER_NAME}-wss"
      - "traefik.http.routers.prodis-${DEVELOPER_NAME}-wss.rule=Host(`prodis.${DEVELOPER_NAME}.phippsy.tech`)"
      - "traefik.http.services.prodis-${DEVELOPER_NAME}-wss.loadbalancer.server.port=443"
      - "traefik.http.routers.prodis-${DEVELOPER_NAME}-wss.entrypoints=websecure"
      - "traefik.http.routers.prodis-${DEVELOPER_NAME}-wss.tls.certresolver=myresolver"
