update postcodes set ndis_zone = 6 where postcode='0803' AND suburb='WAGAIT BEACH' AND state='NT';
update postcodes set ndis_zone = 5 where postcode='0822' AND suburb='MICKET CREEK' AND state='NT';
update postcodes set ndis_zone = 7 where postcode='0852' AND suburb='MINIYERRI' AND state='NT';
update postcodes set ndis_zone = 1 where postcode='1405' AND suburb='CHULLORA' AND state='NSW';
update postcodes set ndis_zone = 1 where postcode='1874' AND suburb='MOOREBANK' AND state='NSW';
update postcodes set ndis_zone = 5 where postcode='2325' AND suburb='YENGO' AND state='NSW';
update postcodes set ndis_zone = 5 where postcode='2347' AND suburb='THIRLDENE' AND state='NSW';
update postcodes set ndis_zone = 2 where postcode='2526' AND suburb='STREAM HILL' AND state='NSW';
update postcodes set ndis_zone = 3 where postcode='2540' AND suburb='BADAGARANG' AND state='NSW';
update postcodes set ndis_zone = 1 where postcode='2556' AND suburb='BRADFIELD' AND state='NSW';
update postcodes set ndis_zone = 1 where postcode='2570' AND suburb='BURRAGORANG VALLEY' AND state='NSW';
update postcodes set ndis_zone = 1 where postcode='2611' AND suburb='MOLONGLO' AND state='ACT';
update postcodes set ndis_zone = 5 where postcode='2787' AND suburb='BELOON' AND state='NSW';
update postcodes set ndis_zone = 5 where postcode='2787' AND suburb='BIMLOW' AND state='NSW';
update postcodes set ndis_zone = 5 where postcode='2787' AND suburb='BINDOOK' AND state='NSW';
update postcodes set ndis_zone = 5 where postcode='2787' AND suburb='BRERETON' AND state='NSW';
update postcodes set ndis_zone = 5 where postcode='2787' AND suburb='JOORILAND' AND state='NSW';
update postcodes set ndis_zone = 5 where postcode='2787' AND suburb='KEDUMBA' AND state='NSW';
update postcodes set ndis_zone = 5 where postcode='2787' AND suburb='KOWMUNG' AND state='NSW';
update postcodes set ndis_zone = 1 where postcode='2911' AND suburb='KENNY' AND state='ACT';
update postcodes set ndis_zone = 2 where postcode='4513' AND suburb='CORYMBIA' AND state='QLD';
update postcodes set ndis_zone = 2 where postcode='4513' AND suburb='GREENSTONE' AND state='QLD';
update postcodes set ndis_zone = 2 where postcode='4513' AND suburb='LILYWOOD' AND state='QLD';
update postcodes set ndis_zone = 2 where postcode='4513' AND suburb='WAGTAIL GROVE' AND state='QLD';
update postcodes set ndis_zone = 2 where postcode='4513' AND suburb='WARABA' AND state='QLD';
update postcodes set ndis_zone = 6 where postcode='4581' AND suburb='K\'GARI' AND state='QLD';
update postcodes set ndis_zone = 1 where postcode='5163' AND suburb='ONKAPARINGA HEIGHTS' AND state='SA';
update postcodes set ndis_zone = 1 where postcode='5801' AND suburb='ADELAIDE' AND state='SA';
update postcodes set ndis_zone = 1 where postcode='6112' AND suburb='DOOBARDA' AND state='WA';
update postcodes set ndis_zone = 5 where postcode='6219' AND suburb='COOKERNUP' AND state='WA';
update postcodes set ndis_zone = 6 where postcode='6350' AND suburb='BULLOCK HILLS' AND state='WA';
update postcodes set ndis_zone = 1 where postcode='6960' AND suburb='MYAREE' AND state='WA';
update postcodes set ndis_zone = 1 where postcode='8383' AND suburb='MELBOURNE' AND state='VIC';
update postcodes set ndis_zone = 1 where postcode='8438' AND suburb='SUNSHINE WEST' AND state='VIC';
update postcodes set ndis_zone = 1 where postcode='8511' AND suburb='SUNSHINE WEST' AND state='VIC';
