name: Restrict Merge to Master

on:
  pull_request:
    branches:
      - master

jobs:
  check-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Check if pull request is from staging
        run: |
          if [[ "${{ github.base_ref }}" == "master" && "${{ github.head_ref }}" != "staging" ]]; then
            echo "Pull requests to master can only be merged from staging"
            exit 1
          fi
